#!/bin/sh
module="dirbtree"
modulepath="/lib/modules/$(uname -r)/kernel/drivers/char/${module}.ko"
rm -f /dev/${module}

if [ ! -f ${modulepath} ]; then
	ln -s $(pwd)/${module}.ko ${modulepath}
fi;
depmod -A
modprobe ${module} || exit 1

major=`cat /proc/devices | awk "\\$2==\"$module\" {print \\$1}"`

mknod /dev/${module} c ${major} 0

chmod 777 /dev/${module}

